FROM python:3.10.13-bookworm

WORKDIR /root/app

# Install dependencies

RUN pip3 install --upgrade pip
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install Flask==3.0.1
RUN pip3 install matplotlib
RUN pip3 install torch
RUN pip3 install torchtext
RUN pip3 install protobuf
#LLM
RUN pip3 install peft==0.7.1
RUN pip3 install trl==0.7.4
RUN pip3 install transformers==4.36.2



# Copy the entire project to the working directory
COPY ./app /root/app  

# CMD tail -f /dev/null
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]



